[
    {
        "age": null,
        "album": "",
        "author": "/u/Just-Zebra-7055",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T20:22:04.830381+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T20:08:11+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>I started a business over a year ago and I set up docker container with a mariadb and a Wordpress image. I modified a plugin to do all the business stuff in it. Well I was moving everything to an AWS since the business is growing and I rebuilt the container. </p> <p>Like a good little software engineer I haven\u2019t backed it up. </p> <p>I do have the volume with the sb files but I have been trying to create an image using the volume. </p> <p>Any help?</p> </div><!-- SC_ON --> &#32; submitted by &#32; <a href=\"https://www.reddit.com/user/Just-Zebra-7055\"> /u/Just-Zebra-7055 </a> <br/> <span><a href=\"https://www.reddit.com/r/docker/comments/1muthw6/help_recovering_files/\">[link]</a></span> &#32; <span><a href=\"https://www.reddit.com/r/docker/comments/1muthw6/help_recovering_files/\">[comments]</a></span>",
        "id": 3368465,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1muthw6/help_recovering_files",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "Help! Recovering files.",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/Da_Badong",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T18:11:42.894559+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T18:08:38+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>I&#39;m trying to build a simple deno app with several other services, so I&#39;m using compose.</p> <p>Here is my compose:</p> <pre><code>services: mongo: ... mongo-express: ... deno-app: build: dockerfile: ./docker/deno/Dockerfile context: . volumes: - .:/app - node_modules:/app/node_modules ports: - &quot;8000:8000&quot; - &quot;5173:5173&quot; environment: - DENO_ENV=development command: [&quot;deno&quot;, &quot;run&quot;, &quot;dev&quot;, &quot;--host&quot;] </code></pre> <p>And here&#39;s my Dockerfile:</p> <pre><code>FROM denoland/deno:latest RUN [&quot;apt&quot;, &quot;update&quot;] RUN [&quot;apt&quot;, &quot;install&quot;, &quot;npm&quot;, &quot;-y&quot;] COPY package.json /app/package.json WORKDIR /app RUN [&quot;npm&quot;, &quot;i&quot;, &quot;-y&quot;] </code></pre> <p>Finally, my work tree:</p> <pre><code>-docker/ -deno/ -Dockerfile -src/ -package.json -docker-compose.yml </code></pre> <p>When I run docker-compose build, everything works",
        "id": 3367398,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1muq5td/need_help_figuring_out_why_my_volume_wont_sync",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "Need help figuring out why my volume won't sync with host",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/Future-_-Risk",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T18:11:43.062889+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T17:55:08+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>Server OS: Arch Linux<br/> Docker Version: 28.3.0</p> <p>Scenario: I have jellyfin readily available over the internet via swag/nginx on a subdomain of my website, it can only be accessed through the URL but I would like to also be able to connect over LAN when I&#39;m on the same network, which I typically am.</p> <p>Docker compose file:</p> <pre><code>version: &quot;3.5&quot; services: jellyfin: image: jellyfin/jellyfin container_name: jellyfin user: &quot;1001:971&quot; ports: - 8096:8096 - 8920:8920 networks: - webserver extra_hosts: - &quot;host.docker.internal:host-gateway&quot; group_add: - &quot;989&quot; devices: - /dev/dri/renderD128:/dev/dri/renderD128 environment: - JELLYFIN_CACHE_DIR=/var/cache/jellyfin - JELLYFIN_CONFIG_DIR=/etc/jellyfin - JELLYFIN_DATA_DIR=/var/lib/jellyfin - JELLYFIN_LOG_DIR=/var/log/jellyfin - JELLYFIN_PublishedServerUrl=http://subdomain.domain.tld volumes: - /home/docker/volume_binds/jellyfin/etc/jellyfin:/etc/jellyf",
        "id": 3367399,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1muprxg/how_to_make_jellyfin_available_on_lan",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "How to make jellyfin available on LAN simultaneously with WAN?",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/operatoralter",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T18:11:42.718459+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T17:41:10+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>Don&#39;t know if this was intended behavior, but the <a href=\"https://hub.docker.com/layers/library/python/3.11-slim/images/sha256-7ae2d10e4bdc6f69ba2daf031647568fec08f3191621d7a5c8760abb236d16ab?context=explore\">python3.11-slim</a> image is now on Debian 13, was previously on Debian 12. Had to update all my references to <a href=\"https://hub.docker.com/layers/library/python/3.11-slim-bookworm/images/sha256-0f05771000c96989ecdde40182e86b1496b4a4c974a9b904441b87683311d130\">python3.11-slim-bookworm</a> (had some external installs that didn&#39;t support 13 yet)</p> </div><!-- SC_ON --> &#32; submitted by &#32; <a href=\"https://www.reddit.com/user/operatoralter\"> /u/operatoralter </a> <br/> <span><a href=\"https://www.reddit.com/r/docker/comments/1mupdnx/psa_python311slim_image_now_on_debian_13/\">[link]</a></span> &#32; <span><a href=\"https://www.reddit.com/r/docker/comments/1mupdnx/psa_python311slim_image_now_on_debian_13/\">[comments]</a></span>",
        "id": 3367397,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1mupdnx/psa_python311slim_image_now_on_debian_13",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "PSA: python3.11-slim image now on Debian 13",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/CommanderKnull",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T14:57:04.829185+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T14:01:03+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>Hi Everyone,</p> <p>I have a small docker swarm with 1 manager node and two worker node, worker node 1 is missing the ingress network. I have restarted the docker service on worker node1 and left-rejoined the swarm but the issue remains the same. The ingress network is encrypted but I don&#39;t think it should be a problem since worker node2 doesn&#39;t have this issue, is it possible to connect to the ingress network manually?</p> <p>Worker node1 are on a separate subnet but these ports are open between worker node1 and the manager node: 2377, 7946, 4789</p> </div><!-- SC_ON --> &#32; submitted by &#32; <a href=\"https://www.reddit.com/user/CommanderKnull\"> /u/CommanderKnull </a> <br/> <span><a href=\"https://www.reddit.com/r/docker/comments/1muja6e/docker_swarm_worker_node_missing_ingress_network/\">[link]</a></span> &#32; <span><a href=\"https://www.reddit.com/r/docker/comments/1muja6e/docker_swarm_worker_node_missing_ingress_network/\">[comments]</a></",
        "id": 3365653,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1muja6e/docker_swarm_worker_node_missing_ingress_network",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "docker swarm worker node missing ingress network",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/ElevenNotes",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T13:51:59.359622+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T13:46:32+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><h1>INTRODUCTION \ud83d\udce2</h1> <p><a href=\"https://github.com/11notes/docker-plex\">11notes/plex</a> a one-stop destination to stream movies, TV shows, and music, Plex is the most comprehensive entertainment platform available today. Available on almost any device, Plex is the first-and-only streaming platform to offer free ad-supported movies, shows, and live TV together with the ability to easily search\u2014and add to your Watchlist\u2014any title ever made, no matter which streaming service it lives on. Using the platform as their entertainment concierge, 17 million (and growing!) monthly active users count on Plex for new discoveries and recommendations from all their favorite streaming apps, personal media libraries, and beyond.</p> <h1>SYNOPSIS \ud83d\udcd6</h1> <p><strong>What can I do with this?</strong> This image will run Plex <a href=\"https://github.com/11notes/RTFM/blob/main/linux/container/image/rootless.md\">rootless</a> for maximum security and performance.</p> <h1>UN",
        "id": 3365036,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1muiwpa/selfhost_plex_fully_rootless_and_30_smaller_than",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "Selfhost Plex, fully rootless and 30% smaller than the most used image!",
        "vote": 0
    },
    {
        "age": null,
        "album": "",
        "author": "/u/Remarkable-Depth8774",
        "bookmarked": false,
        "comments": [],
        "date_created": "2025-08-19T09:34:33.348819+00:00",
        "date_dead_since": null,
        "date_published": "2025-08-19T09:25:36+00:00",
        "description": "<!-- SC_OFF --><div class=\"md\"><p>I am using docker for the deployment of my website. I am using postgresql and the connection string will look something like this (in my env file)</p> <p>postgresql://my_vm_ip:5432/myDbname?user=myuser&amp;password=mypassword </p> <p>my build was sucessful. But when I am making a request from my browser I am getting this weird error. </p> <p>Note : My vm&#39;s port 5432 is active and also I tried changind listen_adress=&quot;*&quot; but this did not work. </p> <p>Can some one help me </p> <p>\u2a2f [Error: Failed query: SELECT </p> <p>n.nspname AS table_schema, </p> <p>c.relname AS table_name, </p> <p>CASE </p> <p>WHEN c.relkind = &#39;r&#39; THEN &#39;table&#39;</p> <p>WHEN c.relkind = &#39;v&#39; THEN &#39;view&#39;</p> <p>WHEN c.relkind = &#39;m&#39; THEN &#39;materialized_view&#39;</p> <p>END AS type,</p> <pre><code>c.relrowsecurity AS rls\\_enabled </code></pre> <p>FROM </p> <p>pg_catalog.pg_class c</p> <p>JOIN </p> <p>pg_catalog.pg_namespace n ON n.oi",
        "id": 3363274,
        "language": "en",
        "link": "https://www.reddit.com/r/docker/comments/1mudk93/docker_postgresql_deployment_error",
        "manual_status_code": 0,
        "page_rating": 27,
        "page_rating_contents": 85,
        "page_rating_visits": 0,
        "page_rating_votes": 0,
        "permanent": false,
        "source__id": 580,
        "source_url": "https://www.reddit.com/r/docker/.rss",
        "status_code": 0,
        "tags": [],
        "thumbnail": null,
        "title": "Docker + Postgresql Deployment Error.",
        "vote": 0
    }
]